language: ruby
dist: trusty
sudo: false
before_install:
  - if [[ $TRAVIS_RUBY_VERSION =~ ^((1|2\.[012]|jruby-1)\.|ree$) ]]; then gem install rubygems-update --version '~> 2.7' --no-document && update_rubygems; else gem update --system; fi
  - gem --version
  - if [[ $TRAVIS_RUBY_VERSION =~ ^((1|2\.[012]|jruby-1)\.|ree$) ]]; then gem install bundler --version '~> 1.17'; else gem install bundler; fi
  - bundle --version
before_script:
  - bundle update
cache: bundler
env:
  global:
    - TESTOPTS=--verbose
rvm:
  - 1.8.7-head
  - 1.9.2-p330
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0-rc2
  - ruby-head
  - jruby-18mode
  - jruby-1.7.27
  - jruby-9.1.17.0
  - jruby-9.2.9.0
  - jruby-head
  - rbx-2.71828182
  - rbx-3.107
  - ree
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2.71828182
