language: ruby
dist: trusty
sudo: false
before_install:
  - gem update --system
  - gem update bundler
before_script:
  - bundle update
cache: bundler
rvm:
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
  - jruby-1.7.27
  - jruby-9.1.15.0
  - jruby-head
  - rbx-3.99
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3.99
