language: ruby
sudo: false
before_script:
  - bundle update
cache: bundler
rvm:
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.1
  - ruby-head
  - jruby-1.7.26
  - jruby-9.1.8.0
  - jruby-head
  - rbx-2.71828182
  - rbx-3.29
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2.71828182
    - rvm: rbx-3.29
