language: ruby
dist: trusty
before_install:
  - if [[ $TRAVIS_RUBY_VERSION =~ ^jruby- && ! $TRAVIS_RUBY_VERSION =~ ^jruby-(1|9\.[01]\.) ]]; then export JRUBY_OPTS=`echo "$JRUBY_OPTS" | sed -E -e 's/--((no)?client|server)//g'`; fi
  - if [[ $TRAVIS_RUBY_VERSION =~ ^jruby- ]]; then echo "JRUBY_OPTS=$JRUBY_OPTS"; fi
  - if [[ $TRAVIS_RUBY_VERSION =~ ^(1|2\.[012]|jruby-(1|9\.0))\. ]]; then gem install rubygems-update --version '~> 2.7' --no-document && update_rubygems; elif [[ ! $TRAVIS_RUBY_VERSION =~ ^truffleruby- ]]; then gem update --system --no-document; fi
  - gem --version
  - if [[ $TRAVIS_RUBY_VERSION =~ ^(1|2\.[012]|jruby-(1|9\.0))\. ]]; then gem install bundler --version '~> 1.17' --no-document; else gem install bundler --no-document; fi
  - bundle --version
before_script:
  - bundle update
cache: bundler
env:
  global:
    - TESTOPTS=--verbose
rvm:
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head
  - jruby-1.7.27
  - jruby-9.0.5.0
  - jruby-9.1.17.0
  - jruby-9.2.10.0
  - jruby-head
  - rbx-3.107
  - truffleruby-20.0.0
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby-20.0.0
