language: ruby
sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y haveged
  - sudo service haveged start
before_script:
  - bundle update
cache: bundler
rvm:
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby-1.7.26
  - jruby-9.1.5.0
  - jruby-head
  - rbx-3.60
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
